apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vortexkv
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: vortexkv
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/vortex-server"
            - "-port"
            - "7379"
            - "-web-port"
            - "7380"
            - "-requirepass"
            - {{ .Values.config.requirepass | quote }}
            - "-maxmemory"
            - {{ .Values.config.maxmemory | quote }}
            - "-aof-path"
            - "/data/vortex.aof"
            - "-aof-fsync"
            - {{ .Values.config.aofFsync | quote }}
          ports:
            - name: redis-wire
              containerPort: 7379
              protocol: TCP
            - name: web-metrics
              containerPort: 7380
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7380
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 7380
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: vortex-data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: vortex-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-vortexkv-data
        {{- end }}
