apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vortexkv
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis-wire
      port: {{ .Values.service.wirePort }}
      targetPort: 7379
      protocol: TCP
    - name: web-metrics
      port: {{ .Values.service.webPort }}
      targetPort: 7380
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
